name: "Meta-Cedille tests"
on:
  pull_request:
  push:
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-21.11
    - uses: cachix/cachix-action@v10
      with:
        name: whatisrt
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-build -A meta-cedille
    - run: nix-build -A tests
    - run: nix-shell --run "echo OK"

  Benchmarks:
    needs: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-21.11
    - uses: cachix/cachix-action@v10
      with:
        name: whatisrt
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-build -A benchmarks -o bench
    - name: Archive times
      uses: actions/upload-artifact@v3
      with:
        name: times
        path: bench/test-time*
